services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
    restart: always
    env_file:
      - ".env"
    networks:
      - app-network

  nginx:
    container_name: nginx_container
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    links:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    container_name: laravel_app
    build: docker/php
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
